project_name: wifiqr
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: macos
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip