project_name: wifiqr
builds:
  - main: ./cmd/wifiqr
    ldflags:
      - -s -w -X main.version={{.Version}}
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
archives:
  - replacements:
      darwin: macos
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip